# Shell and terminal
brew "antidote"
brew "coreutils"
brew "findutils"
brew "gawk"
brew "git"
brew "ghostscript"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "htop"
brew "make"
brew "starship"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

# Development tools and libraries
tap "coursier/formulas"
brew "ack"
brew "aspell"
brew "automake"
brew "boehmgc"
brew "cmake"
brew "coursier/formulas/coursier"
brew "ffmpeg"
brew "gmp"
brew "gnutls"
brew "graphicsmagick"
brew "jq"
brew "libffi"
brew "llvm"
brew "mise"
brew "mono-libgdiplus"
brew "pkg-config"
brew "readline"
brew "rename"
brew "sqlite"
brew "transmission-cli"
brew "trash"
brew "uv"
brew "xz"
brew "zlib"

# Editors and developer applications
brew "emacs"
cask "docker"
cask "dotnet-sdk"
cask "git-credential-manager"
cask "insomnia"
cask "iterm2"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# Desktop applications
cask "cyberduck"
cask "discord"
cask "firefox"
cask "freedom"
cask "google-chrome"
cask "hyperkey"
cask "macfuse"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "rectangle"
cask "skim"
cask "vlc"
cask "zotero"

# Fonts and Python command-line applications
cask "font-hack-nerd-font"
uv "ipython"
uv "poetry"
