# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Source every file in .bash.d
for f in `find ~/.bash.d/ -type f`; do source $f; done
