# >>> JVM installed by coursier >>>
export JAVA_HOME="/Users/sathomso/Library/Caches/Coursier/arc/https/github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_mac_hotspot_8u292b10.tar.gz/jdk8u292-b10/Contents/Home"
# <<< JVM installed by coursier <<<

# >>> coursier install directory >>>
export PATH="$PATH:/Users/sathomso/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<

