# Source every file in .bash.d
for f in `find ~/.zsh.d/ -type f`; do
	source $f
done

if [[ "$(uname)" == "Darwin" ]]
then
  BREW=$(brew --prefix)
  Z="${BREW}/etc/profile.d/z.sh"  # confusingly for z, not zsh
  if [ -e "${Z}" ]
  then
    source "${Z}"
  fi
fi

source "${HOME}/code/dotfiles/lib/antigen/antigen.zsh"

antigen use oh-my-zsh

# antigen theme mh
antigen theme blinks

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle z
antigen bundle common-aliases
antigen bundle git
antigen bundle brew
if [[ "$(uname)" == "Linux" ]]; then
  antigen bundle command-not-found  # Ubuntu only
fi
if [[ "$(uname)" == "Darwin" ]]; then
	antigen bundle osx  # OSX only
fi
antigen bundle scala
antigen bundle sbt
antigen bundle mvn
antigen bundle tmux
antigen bundle cabal
antigen bundle jsontools
antigen bundle Tarrasch/zsh-autoenv
antigen-bundle Tarrasch/zsh-functional


antigen apply
