# Source every file in .bash.d
for f in `find ~/.zsh.d/ -type f`; do source $f; done

if [ -z `which brew` ]
then
	export BREW="/usr/local"
else
	export BREW=$(brew --prefix)
fi

if [ -e ${BREW}/share/antigen.zsh ]
then
	source ${BREW}/share/antigen.zsh
fi
if [ -e ${BREW}/etc/profile.d/z.sh ]
then
	source ${BREW}/etc/profile.d/z.sh
fi


antigen use oh-my-zsh

# antigen theme mh
antigen theme blinks

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle z
antigen bundle common-aliases
antigen bundle git
antigen bundle brew
# antigen bundle command-not-found  # Ubuntu only
antigen bundle osx  # OSX only, obvs
antigen bundle Tarrasch/zsh-autoenv
antigen bundle scala
antigen bundle sbt
antigen bundle mvn
antigen bundle tmux
antigen bundle cabal
antigen bundle jsontools
# antigen bundle virtualenvwrapper
antigen bundle web-search


antigen apply
