#export OPEN_FST_HOME="/opt/openfst/openfst-1.3.2" # "/opt/openfst/openfst-1.4.1"
#export PREFIX="${OPEN_FST_HOME}"
#export CPLUS_INCLUDE_PATH="${OPEN_FST_HOME}/include:$CPLUS_INCLUDE_PATH"
#export LD_LIBRARY_PATH="${OPEN_FST_HOME}/lib:$LD_LIBRARY_PATH"
#export LD_LIBRARY_PATH="${OPEN_FST_HOME}/lib/fst:$LD_LIBRARY_PATH"
#export LIBRARY_PATH="${LD_LIBRARY_PATH}"
#export PATH="$PATH:${OPEN_FST_HOME}/bin"
