# export GRB_LICENSE_FILE="${HOME}/.config/gurobi.lic"
# # export GUROBI_HOME="/opt/gurobi/current/linux64"
# export GUROBI_HOME="/Library/gurobi602/mac64"
# export PATH="${PATH}:${GUROBI_HOME}/bin"
# export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
